port: "8080"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "storage"
  sslmode: "disable"
  password: "your db password"

endpoint: "localhost:9000"
accessKeyId: "minioadmin"
secretaccessKeyId: "password"
